Dev
Pashax12/WebEncounterCreator pull request #6
Opened 2022-03-23 13:23 UTC by Pashax12

2022-03-23 13:23 UTC, Pashax12 commented
Renamed test and rebased UserService

2022-03-24 07:57 UTC, AntonBulavko requested changes

2022-03-24 07:57 UTC, AntonBulavko commented on src/main/java/by/paul/monsterservice/entity/EncounterSetup.java
> +public class EncounterSetup {
имя класса - существительное
имя метода - действие
EncounterSetup звучит как действие

2022-03-24 07:57 UTC, AntonBulavko commented on src/main/java/by/paul/monsterservice/controller/MonsterController.java
>    @PostMapping("/usermonster")
https://yalantis.com/blog/how-to-create-a-restful-api/ параграф про endpoints

2022-03-24 07:57 UTC, AntonBulavko commented on src/main/java/by/paul/monsterservice/service/user/UserService.java
> +      response.put("status", uniqueResponse);
зачем, если у тебя есть ExceptionAdvice и ты можешь создать кастомное исключение из разряда - UserExistByUsernameException, отловить его и в эксепшн хэндлере засетать нужный статус, а результатом этого метода можно возвращать объект, который сохранился в бд

2022-03-24 08:03 UTC, AntonBulavko commented on src/main/resources/application.yaml
> +  addUser:
оставил коммент про это чуть выше

2022-03-25 10:34 UTC, AntonBulavko requested changes

2022-03-25 10:34 UTC, AntonBulavko commented on src/main/java/by/paul/monsterservice/controller/ExceptionAdvice.java
> +  @ExceptionHandler(UsernameNotFoundException.class)
если по результатам ошибки нет никакой доп логики, и везде одинаковый статус, то можно передать все исключения массивом и будет один метод для обработки трех исключений

2022-03-25 10:34 UTC, AntonBulavko commented on src/main/java/by/paul/monsterservice/controller/MonsterController.java
>    @PostMapping("/monsterlibrary")
более restful было бы /monsters + у тебя 2 метода в контроллере, которые по сути делают одно и тоже (возвращают монстров по какому-то параметру)

2022-03-25 10:34 UTC, AntonBulavko commented on src/main/java/by/paul/monsterservice/controller/MonsterController.java
>    @GetMapping("/monsterlibrary/{path}")
/monsters/{name} ты же монстра по имени ищешь, а не по пути

2022-03-28 07:40 UTC, merged